### ISSUE TITLE
matplotlib: support 2D signal plots

### ISSUE THREAD

**Issue by balthazarneveu** [balthazarneveu/interactive_pipe#14]
# Description
You may want to plot some signals along with your images...

Several ways to make this happen:
1. a filter could return a Signal instance... Signal(x= ..., y=...) , exactly like you'd pass to matplotlib. This will allow combining several signals together by the way. :+1: 
2. Another trick would be to return a dictionary ... some a library remains a library and does not depend on the interactive_pipe Signal class. :thinking:  but this may actually make things harder to read...

# Todo
- [x] write Curve class (efaf685e671887ec4da8c3258541247212eebb40)
- [x] pytest Curve class
- [x] plug Curve into interactive pipe outputs (fa5346b67be707aa33fad6f3ee5e198bc1ef5638)
- [x] If title is provided, override default title  (a1ca687e2d1ad061c16ef2222878ebb2e95e8b52) 
- [x] support Curve in qt backend
- [x] Easier access to some attributes (.data["grid"] -> .grid)
