### ISSUE TITLE
keyboard controllers

### ISSUE THREAD

**Issue by balthazarneveu** [balthazarneveu/interactive_pipe#4]
## Tasks
- [x] add special keyboard controls
- [x] ON/OFF (True/False) with a single key
- [x] str list with modulo
- [x] int sliders
- [x] Qt Backend
- [x] Qt backend updates on labels
- [x] Display help properly
- [x] Matplotlib backend
- [x] pageup , pagedown, up , down are supported
# Description
use a special Control class to use a key (or 2 keys) to control an underlying
- a slider (up/down)
- a slider with a single key: to navigate like next , next, next, go back to the begining.
- a tickbox toggle (true/false when pressing A for instance)
- a dropdown list (to navigate next , next, next, go back to the begining)

```python
@interactive(
    rotation = Control(ROTATIONS[0], ROTATIONS, name="rotation")
)
```

can become 

```python
@interactive(
    rotation = KeyboardSlider(ROTATIONS[0], ROTATIONS, name="rotation", keydown="-", keyup="+", modulo=True)
)
```

:gift:  added the QT info box to view shortcuts information. Keyboard sliders appear here
<img src="https://github.com/balthazarneveu/interactive_pipe/assets/41070742/eada572a-0152-4fd4-9b25-1760d78cccc4" width=300>
